name: trail

services:
  backend:
    image: mimir/backend
    build: .
    container_name: mimir-backend
    environment:
      - "RAILS_ENV=development"
      - "DB_HOST=db"
      - "DB_USERNAME=postgres"
      - "DB_NAME=mimir"
      - "LAUNCHY_DRY_RUN=true"
      - "BROWSER=/dev/null"
    depends_on:
      - db
    tty: true
    stdin_open: true
    volumes:
      - .:/rails
    ports:
      - 3001:3001

  db:
    image: postgres:15-alpine
    container_name: mimir-postgres
    restart: unless-stopped
    volumes:
      - mimir-postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=mimir"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "PAGER=less"
    ports:
      - 5432:5432

volumes:
  mimir-postgres-data: